### ISSUE TITLE
Canciones bloqueadas en playlists favoritas

### ISSUE THREAD

**Issue by efoppiano** [taller2-grupo5-rostov-1c2022/songs-server#14]
Cuando agregás a favoritos una playlist con una canción, y después bloquean esa canción, al hacer GET de las playlists favoritas sale la canción bloqueada, aunque no seas admin

**Comment by FacuMastri** [comment]
Esto al final que paso?

**Comment by efoppiano** [comment]
> Esto al final que paso?

Fixeado
